// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoSocioEconomico.Infrastructure.Data;

#nullable disable

namespace ProyectoSocioEconomico.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260326060057_AgregarImagenPerfilUsuario")]
    partial class AgregarImagenPerfilUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CasosPrograma", b =>
                {
                    b.Property<int>("IdCaso")
                        .HasColumnType("int");

                    b.Property<int>("IdPrograma")
                        .HasColumnType("int");

                    b.HasKey("IdCaso", "IdPrograma");

                    b.HasIndex(new[] { "IdPrograma" }, "IX_CasosProgramas_IdPrograma");

                    b.ToTable("CasosProgramas", (string)null);
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Caso", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaLimite")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBeneficiado")
                        .HasColumnType("int");

                    b.Property<int>("IdCategoria")
                        .HasColumnType("int");

                    b.Property<string>("ImagenUrl")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<decimal>("Meta")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdBeneficiado" }, "IX_Casos_IdBeneficiado");

                    b.HasIndex(new[] { "IdCategoria" }, "IX_Casos_IdCategoria");

                    b.ToTable("Casos");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Comprobante", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CodigoComprobante")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("DonacionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("FechaSubida")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdDonacion")
                        .HasColumnType("int");

                    b.Property<string>("UrlArchivo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "DonacionId" }, "IX_Comprobantes_DonacionId");

                    b.ToTable("Comprobantes");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Donacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Anonimo")
                        .HasColumnType("bit");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaDonacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdCaso")
                        .HasColumnType("int");

                    b.Property<int>("IdDonador")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdCaso" }, "IX_Donaciones_IdCaso");

                    b.HasIndex(new[] { "IdDonador" }, "IX_Donaciones_IdDonador");

                    b.ToTable("Donaciones");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.InscripcionesVoluntario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaInscripcion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdPrograma")
                        .HasColumnType("int");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdPrograma" }, "IX_InscripcionesVoluntarios_IdPrograma");

                    b.HasIndex(new[] { "IdUsuario" }, "IX_InscripcionesVoluntarios_IdUsuario");

                    b.ToTable("InscripcionesVoluntarios");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.LogsFinanciero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<int>("ReferenciaId")
                        .HasColumnType("int");

                    b.Property<string>("TipoMovimiento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("LogsFinancieros");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Notificacione", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaEnvio")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdUsuario")
                        .HasColumnType("int");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("nvarchar(max)")
                        .HasDefaultValue("");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "UsuarioId" }, "IX_Notificaciones_UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Programa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPor")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImagenUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "CreadoPor" }, "IX_Programas_CreadoPor");

                    b.ToTable("Programas");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Retiro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("DatosPago")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("FechaProcesado")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaSolicitud")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdBeneficiado")
                        .HasColumnType("int");

                    b.Property<int>("IdCaso")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdBeneficiado" }, "IX_Retiros_IdBeneficiado");

                    b.HasIndex(new[] { "IdCaso" }, "IX_Retiros_IdCaso");

                    b.ToTable("Retiros");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Direccion")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Dui")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("DUI");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<int>("IdRol")
                        .HasColumnType("int");

                    b.Property<string>("ImagenPerfil")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Telefono")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id");

                    b.HasIndex(new[] { "IdRol" }, "IX_Usuarios_IdRol");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("CasosPrograma", b =>
                {
                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Caso", null)
                        .WithMany()
                        .HasForeignKey("IdCaso")
                        .IsRequired();

                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Programa", null)
                        .WithMany()
                        .HasForeignKey("IdPrograma")
                        .IsRequired();
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Caso", b =>
                {
                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Usuario", "IdBeneficiadoNavigation")
                        .WithMany("Casos")
                        .HasForeignKey("IdBeneficiado")
                        .IsRequired();

                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Categoria", "IdCategoriaNavigation")
                        .WithMany("Casos")
                        .HasForeignKey("IdCategoria")
                        .IsRequired();

                    b.Navigation("IdBeneficiadoNavigation");

                    b.Navigation("IdCategoriaNavigation");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Comprobante", b =>
                {
                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Donacione", "Donacion")
                        .WithMany("Comprobantes")
                        .HasForeignKey("DonacionId")
                        .IsRequired();

                    b.Navigation("Donacion");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Donacione", b =>
                {
                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Caso", "IdCasoNavigation")
                        .WithMany("Donaciones")
                        .HasForeignKey("IdCaso")
                        .IsRequired();

                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Usuario", "IdDonadorNavigation")
                        .WithMany("Donaciones")
                        .HasForeignKey("IdDonador")
                        .IsRequired();

                    b.Navigation("IdCasoNavigation");

                    b.Navigation("IdDonadorNavigation");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.InscripcionesVoluntario", b =>
                {
                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Programa", "IdProgramaNavigation")
                        .WithMany("InscripcionesVoluntarios")
                        .HasForeignKey("IdPrograma")
                        .IsRequired();

                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Usuario", "IdUsuarioNavigation")
                        .WithMany("InscripcionesVoluntarios")
                        .HasForeignKey("IdUsuario")
                        .IsRequired();

                    b.Navigation("IdProgramaNavigation");

                    b.Navigation("IdUsuarioNavigation");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Notificacione", b =>
                {
                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Programa", b =>
                {
                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Usuario", "CreadoPorNavigation")
                        .WithMany("Programas")
                        .HasForeignKey("CreadoPor")
                        .IsRequired();

                    b.Navigation("CreadoPorNavigation");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Retiro", b =>
                {
                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Usuario", "IdBeneficiadoNavigation")
                        .WithMany("Retiros")
                        .HasForeignKey("IdBeneficiado")
                        .IsRequired();

                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Caso", "IdCasoNavigation")
                        .WithMany("Retiros")
                        .HasForeignKey("IdCaso")
                        .IsRequired();

                    b.Navigation("IdBeneficiadoNavigation");

                    b.Navigation("IdCasoNavigation");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("ProyectoSocioEconomico.Domain.Entities.Role", "IdRolNavigation")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdRol")
                        .IsRequired();

                    b.Navigation("IdRolNavigation");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Caso", b =>
                {
                    b.Navigation("Donaciones");

                    b.Navigation("Retiros");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Casos");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Donacione", b =>
                {
                    b.Navigation("Comprobantes");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Programa", b =>
                {
                    b.Navigation("InscripcionesVoluntarios");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Role", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("ProyectoSocioEconomico.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Casos");

                    b.Navigation("Donaciones");

                    b.Navigation("InscripcionesVoluntarios");

                    b.Navigation("Notificaciones");

                    b.Navigation("Programas");

                    b.Navigation("Retiros");
                });
#pragma warning restore 612, 618
        }
    }
}
